"""
RAG Pipeline — Facade

Thin facade wiring FAISSIndexStore and DocumentRetriever together.

Preserves the public API of the original RAGPipeline so that callers
(bootstrap orchestrator, PMPDAssembler) require minimal changes:

    # Old:
    pipeline = RAGPipeline.from_policy_config(config_dict)
    db, meta = pipeline.build_or_load_index(tree_path, policy_name)
    docs     = pipeline.search_similar_documents(query)
    stats    = pipeline.get_index_stats()

    # New (same external API):
    pipeline = RAGPipeline.from_tuner_config(config_dict)
    db, meta = pipeline.build_or_load_index(tree_path, policy_name)
    docs     = pipeline.search_similar_documents(query)
    stats    = pipeline.get_index_stats()

The EnhancedRAGPipeline backwards-compatibility alias is preserved.
"""

from __future__ import annotations

from langchain_core.documents import Document

from rag.config import RAGConfig
from rag.index_store import FAISSIndexStore
from rag.retriever import DocumentRetriever


class RAGPipeline:
    """
    Policy-agnostic RAG pipeline for red-teaming document retrieval.

    Builds and maintains a FAISS vector index from structured Markdown
    files generated by PolicyIngester.  Works with any policy domain.

    Instantiate directly with a RAGConfig, or use from_tuner_config()
    when using LLM-tuned parameters from RAGTuner.

    Usage
    -----
        config   = RAGConfig.default()
        pipeline = RAGPipeline(config)
        db, meta = pipeline.build_or_load_index("policy/md_tree", "policy")
        docs     = pipeline.search_similar_documents("user query")
    """

    def __init__(self, config: RAGConfig | None = None) -> None:
        """
        Args:
            config: RAGConfig instance. Defaults to RAGConfig.default().
        """
        self._config = config or RAGConfig.default()
        self._store = FAISSIndexStore(self._config)
        self._retriever: DocumentRetriever | None = None

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def from_tuner_config(
        cls,
        config_dict: dict,
        embeddings_model: str = "sentence-transformers/all-mpnet-base-v2",
    ) -> RAGPipeline:
        """
        Instantiate pipeline from a RAGTuner result dict.

        Replaces the original from_policy_config() classmethod — name updated
        to reflect that the dict comes from RAGTuner specifically.
        The old name is aliased below for backwards compatibility.

        Args:
            config_dict:      Dict with chunk_size, chunk_overlap, k, rationale.
            embeddings_model: HuggingFace embeddings model name.

        Returns:
            Configured RAGPipeline instance.
        """
        config = RAGConfig(
            chunk_size=int(config_dict.get("chunk_size", 1024)),
            chunk_overlap=int(config_dict.get("chunk_overlap", 256)),
            default_k=int(config_dict.get("k", 5)),
            embeddings_model=embeddings_model,
            rationale=config_dict.get("rationale", ""),
        )
        instance = cls(config)
        print(
            f"  ✅ RAG pipeline configured:\n"
            f"     chunk_size={config.chunk_size}, "
            f"chunk_overlap={config.chunk_overlap}, "
            f"k={config.default_k}\n"
            f"     Rationale: {config.rationale}"
        )
        return instance

    # Backwards-compatibility alias — original name used in main.py
    from_policy_config = from_tuner_config

    # ------------------------------------------------------------------
    # Index lifecycle
    # ------------------------------------------------------------------

    def build_or_load_index(
        self,
        tree_path: str,
        policy_name: str = "policy",
        timing_info: list[str] | None = None,
        force_rebuild: bool = False,
    ) -> tuple:
        """
        Build vector index from Markdown files or load a cached version.

        Args:
            tree_path:     Path to the Markdown tree root directory.
            policy_name:   Identifier used for the cache directory name.
            timing_info:   Optional list to append timing strings to.
            force_rebuild: If True, ignore cache and rebuild from scratch.

        Returns:
            Tuple of (FAISS database, metadata dict).
        """
        db, meta = self._store.build_or_load(
            tree_path=tree_path,
            policy_name=policy_name,
            timing_info=timing_info,
            force_rebuild=force_rebuild,
        )
        self._retriever = DocumentRetriever(db, self._config)
        return db, meta

    # ------------------------------------------------------------------
    # Retrieval
    # ------------------------------------------------------------------

    def search_similar_documents(
        self,
        query: str,
        k: int | None = None,
        filter_category: str | None = None,
    ) -> list[Document]:
        """
        Retrieve the most relevant document chunks for a query.

        Args:
            query:           Search query string.
            k:               Number of documents to retrieve.
            filter_category: Optional category filter.

        Returns:
            List of most relevant Document objects.

        Raises:
            RuntimeError: If build_or_load_index() has not been called.
        """
        if self._retriever is None:
            raise RuntimeError("Index not built. Call build_or_load_index() first.")
        return self._retriever.search(query, k=k, filter_category=filter_category)

    def get_category_documents(
        self,
        category: str,
        k: int = 10,
    ) -> list[Document]:
        """
        Retrieve documents from a specific category.

        Args:
            category: Category name, e.g. "hazards", "definitions", "meta".
            k:        Maximum number of documents to return.

        Returns:
            List of Document objects from the specified category.

        Raises:
            RuntimeError: If build_or_load_index() has not been called.
        """
        if self._retriever is None:
            raise RuntimeError("Index not built. Call build_or_load_index() first.")
        return self._retriever.get_by_category(category, limit=k)

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------

    def get_index_stats(self) -> dict:
        """
        Get statistics about the current index.

        Returns:
            Dict with index statistics, or {"status": "not_built"}.
        """
        if self._retriever is None:
            return {"status": "not_built"}
        return self._retriever.stats()


# ---------------------------------------------------------------------------
# Backwards compatibility alias
# ---------------------------------------------------------------------------

# If any existing code imports EnhancedRAGPipeline, this keeps it working.
EnhancedRAGPipeline = RAGPipeline
