"""
Core Enumerations

Replaces raw string literals used as typed values throughout the project.
Using str-based enums means existing string comparisons (e.g. == "violation")
continue to work during the incremental refactor — no flag day required.

Enums defined here:
  - Verdict        : Judge Agent verdict values
  - OneShotSource  : Origin of a OneShot example
  - BootstrapModel : Canonical LLM identifiers used across bootstrap modules

Design note
───────────
All enums inherit from (str, Enum) so that:
  1. Enum members compare equal to their string values.
  2. JSON serialisation works without a custom encoder.
  3. Existing code using raw string literals is not broken during migration.
"""

from __future__ import annotations

from enum import Enum

# ---------------------------------------------------------------------------
# Verdict
# ---------------------------------------------------------------------------


class Verdict(str, Enum):
    """
    Possible outcomes of a Judge Agent evaluation.

    Used in:
      - OneShot.verdict
      - PMPD.record_verdict()
      - PolicyDebate result dicts
      - _record_verdict_to_pmpd() in bootstrap orchestrator
    """

    VIOLATION = "violation"
    COMPLIANT = "compliant"
    BORDERLINE = "borderline"


# ---------------------------------------------------------------------------
# OneShotSource
# ---------------------------------------------------------------------------


class OneShotSource(str, Enum):
    """
    Origin of a OneShot example stored in a CategoryModule.

    SHADOW : Pre-written seed example authored at parse time.
             Stable ground truth for the category.
    LIVE   : Generated by the Judge Agent during a real evaluation.
             Accumulates over time — the dynamic feedback loop.

    Used in:
      - OneShot.source
      - CategoryModule.get_shadow_shots()
      - CategoryModule.get_live_shots()
    """

    SHADOW = "shadow"
    LIVE = "live"


# ---------------------------------------------------------------------------
# JudgeSeverity
# ---------------------------------------------------------------------------


class JudgeSeverity(str, Enum):
    """
    Structured severity levels returned by the Judge Agent in the verdict block.

    Maps to integer severity for PMPD storage via SEVERITY_TO_INT.

    Used in:
      - PolicyDebate verdict parsing
      - _record_verdict_to_pmpd() severity mapping
      - PMPD.record_verdict() severity argument
    """

    SAFE = "SAFE"
    BORDERLINE = "BORDERLINE"
    UNSAFE = "UNSAFE"


# Convenience mapping — replaces _verdict_to_severity_int() in pmpd_main.py
SEVERITY_TO_INT: dict[JudgeSeverity, int] = {
    JudgeSeverity.SAFE: 1,
    JudgeSeverity.BORDERLINE: 3,
    JudgeSeverity.UNSAFE: 5,
}

# Maps Judge severity strings to PMPD Verdict strings
SEVERITY_TO_VERDICT: dict[JudgeSeverity, Verdict] = {
    JudgeSeverity.SAFE: Verdict.COMPLIANT,
    JudgeSeverity.BORDERLINE: Verdict.BORDERLINE,
    JudgeSeverity.UNSAFE: Verdict.VIOLATION,
}


# ---------------------------------------------------------------------------
# BootstrapModel
# ---------------------------------------------------------------------------


class BootstrapModel(str, Enum):
    """
    Canonical LLM identifiers used during the bootstrap pipeline.

    Centralises the three different model strings that were previously
    defined as separate constants (BOOTSTRAP_MODEL, PARSER_MODEL) in
    policy_ingester.py, prompt_generator.py, and pmpd_parser.py —
    with inconsistent :free suffixes.

    Usage:
        client.call_model(model=BootstrapModel.LLAMA_70B, ...)
    """

    # Meta-Llama 3.3 70B — used for structure planning, section routing,
    # prompt generation, and PMPD extraction.
    # The :free suffix is intentionally omitted here; use LLAMA_70B_FREE
    # if the OpenRouter free tier is preferred for non-critical calls.
    LLAMA_70B = "meta-llama/llama-3.3-70b-instruct"
    LLAMA_70B_FREE = "meta-llama/llama-3.3-70b-instruct:free"

    # Default debate model
    GPT_OSS_20B = "openai/gpt-oss-20b"



"""
New enums to ADD to core/enums.py
Append these after the BootstrapModel class.
Do not remove any existing enums.
"""


# ---------------------------------------------------------------------------
# PromptStyle
# ---------------------------------------------------------------------------

class PromptStyle(str, Enum):
    """
    Prompt construction style used by the debate agents.

    HARMONY  : Uses OpenAI Harmony format with system/developer role
               separation. Recommended for gpt-oss models.
               Controlled by COURTGUARD_USE_HARMONY_ROLES=true in .env
    STANDARD : Classic system+user format. Used by all other models
               and as a fallback when harmony roles are unavailable.
    """

    HARMONY  = "harmony"
    STANDARD = "standard"


# ---------------------------------------------------------------------------
# AgentRole
# ---------------------------------------------------------------------------

class AgentRole(str, Enum):
    """
    Role of a debate agent in the evaluation pipeline.

    ATTACKER : Initial screener — sees all categories in lite form.
               Goal: flag potential violations sensitively.
    DEFENDER : Precise evaluator — sees only flagged categories in full.
               Goal: confirm or overturn the attacker's accusation.
               Holds final authority.
    JUDGE    : Optional third agent — called only on tie resolution
               when COURTGUARD_TIE_WINNER=judge.
               Not used in standard PMPD two-agent flow.
    """

    ATTACKER = "attacker"
    DEFENDER = "defender"
    JUDGE    = "judge"


# ---------------------------------------------------------------------------
# OneShotPolarity
# ---------------------------------------------------------------------------

class OneShotPolarity(str, Enum):
    """
    Polarity of a OneShot example stored in a CategoryModule.

    POSITIVE : Example of a policy VIOLATION — what the model should flag.
    NEGATIVE : Example of COMPLIANT content — what the model should allow.

    Both are provided to the Defender to ground its evaluation in
    concrete policy boundaries.

    Note: The existing OneShotSource enum tracks origin (shadow/live).
    OneShotPolarity tracks content type (violation/compliant example).
    These two dimensions are orthogonal — a live shot can be positive
    or negative depending on its verdict.
    """

    POSITIVE = "positive"   # violation example
    NEGATIVE = "negative"   # compliant example


# ---------------------------------------------------------------------------
# TieWinner
# ---------------------------------------------------------------------------

class TieWinner(str, Enum):
    """
    Policy for resolving a tie when all debate rounds are exhausted.

    In the standard PMPD flow this should never trigger because the
    Defender holds final authority. TieWinner is only relevant if
    future extensions add symmetrical round structures.

    DEFENDER : Safe-by-default — if defender never confirmed, result is SAFE.
               Recommended for most safety evaluation tasks.
    ATTACKER : Flag-by-default — if attacker accused and was never
               definitively overturned, result is UNSAFE.
    JUDGE    : Call the optional Judge agent to break the tie.

    Controlled by COURTGUARD_TIE_WINNER in .env.
    """

    DEFENDER = "defender"
    ATTACKER = "attacker"
    JUDGE    = "judge"


# ---------------------------------------------------------------------------
# DebateOutcome
# ---------------------------------------------------------------------------

class DebateOutcome(str, Enum):
    """
    Final outcome of a PMPD debate evaluation.

    SAFE       : Defender confirmed the content is compliant.
    UNSAFE     : Defender confirmed a violation.
    EARLY_SAFE : Attacker found no violation — Defender was never called.
    ERROR      : Debate could not complete due to API or parsing failure.
    """

    SAFE       = "SAFE"
    UNSAFE     = "UNSAFE"
    EARLY_SAFE = "EARLY_SAFE"
    ERROR      = "ERROR"